-- Учёт материалов: категории, справочник материалов, журнал движений, заявки на закупку.
-- Справочник и остатки загружены разово из рабочей Excel-таблицы студии.
-- Для категорий НЗ-запас (аккаунтская) и Материалы для МК дата последнего пересчёта
-- проставлена как 2026-10-02 (инвентаризация проведена в этот день со слов администратора).

CREATE TABLE public.material_categories (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE public.materials (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  category_id BIGINT REFERENCES public.material_categories(id),
  name TEXT NOT NULL,
  color_number TEXT,
  unit TEXT NOT NULL DEFAULT 'шт',
  qty_full NUMERIC NOT NULL DEFAULT 0,
  qty_half NUMERIC,
  qty_almost_empty NUMERIC,
  min_threshold NUMERIC,
  last_counted_at DATE,
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE public.material_transactions (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  material_id BIGINT NOT NULL REFERENCES public.materials(id) ON DELETE CASCADE,
  type TEXT NOT NULL, -- приход | расход | корректировка
  field TEXT NOT NULL DEFAULT 'qty_full', -- qty_full | qty_half | qty_almost_empty
  delta NUMERIC NOT NULL,
  comment TEXT,
  client_id BIGINT REFERENCES public.clients(id),
  created_by UUID,
  created_by_name TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE public.purchase_requests (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  cycle_label TEXT NOT NULL,
  material_id BIGINT REFERENCES public.materials(id),
  material_name_manual TEXT,
  needed_qty NUMERIC NOT NULL DEFAULT 0,
  available_qty NUMERIC,
  status TEXT NOT NULL DEFAULT 'новая', -- новая | заказано | куплено
  requested_by UUID,
  requested_by_name TEXT,
  note TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.material_categories ENABLE ROW LEVEL SECURITY;
CREATE POLICY "auth_all" ON public.material_categories FOR ALL TO authenticated USING (true) WITH CHECK (true);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.material_categories TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.material_categories TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.material_categories_id_seq TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.material_categories_id_seq TO service_role;

ALTER TABLE public.materials ENABLE ROW LEVEL SECURITY;
CREATE POLICY "auth_all" ON public.materials FOR ALL TO authenticated USING (true) WITH CHECK (true);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.materials TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.materials TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.materials_id_seq TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.materials_id_seq TO service_role;

ALTER TABLE public.material_transactions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "auth_all" ON public.material_transactions FOR ALL TO authenticated USING (true) WITH CHECK (true);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.material_transactions TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.material_transactions TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.material_transactions_id_seq TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.material_transactions_id_seq TO service_role;

ALTER TABLE public.purchase_requests ENABLE ROW LEVEL SECURITY;
CREATE POLICY "auth_all" ON public.purchase_requests FOR ALL TO authenticated USING (true) WITH CHECK (true);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.purchase_requests TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.purchase_requests TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.purchase_requests_id_seq TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.purchase_requests_id_seq TO service_role;

-- Категории
INSERT INTO public.material_categories (name, sort_order) VALUES
  ('Масло', 0),
  ('Акрил', 1),
  ('Гуашь', 2),
  ('Акварель', 3),
  ('Акрил по ткани', 4),
  ('Бумага', 5),
  ('Холсты', 6),
  ('Аккаунтская (НЗ запас)', 7),
  ('Кисти', 8),
  ('Карандаши', 9),
  ('Прочие худ.материалы', 10),
  ('Канцелярия', 11),
  ('Хоз.Товары', 12),
  ('Материалы для МК', 13);

-- Материалы
INSERT INTO public.materials (category_id, name, color_number, unit, qty_full, qty_half, qty_almost_empty, last_counted_at, notes) VALUES
  ((SELECT id FROM public.material_categories WHERE name = 'Масло'), 'Ладога', NULL, 'тюбик', 0, NULL, NULL, '2026-10-01', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Масло'), 'Кадмий красный темный', '303', 'тюбик', 1.0, NULL, NULL, '2026-10-01', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Масло'), 'английская красная', '300', 'тюбик', 0, NULL, 1.0, '2026-10-01', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Масло'), 'Кадмий желтый темный', '202', 'тюбик', 0, NULL, NULL, '2026-10-01', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Масло'), 'Кадмий оранжевый', '304', 'тюбик', 0, NULL, 1.0, '2026-10-01', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Масло'), 'Кадмий желтый средний', '201', 'тюбик', 1.0, NULL, NULL, '2026-10-01', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Масло'), 'Неополитанская светло-желтая', '219', 'тюбик', 0, NULL, NULL, '2026-10-01', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Масло'), 'Голубая фц', '500', 'тюбик', 0, NULL, NULL, '2026-10-01', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Масло'), 'небесно-голубая', '512', 'тюбик', 1.0, 1.0, NULL, '2026-10-01', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Масло'), 'кобальт синий средний', '505', 'тюбик', 0, NULL, 1.0, '2026-10-01', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Масло'), 'Индиго', '516', 'тюбик', 0, NULL, NULL, '2026-10-01', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Масло'), 'Брауберг', NULL, 'тюбик', 0, NULL, NULL, '2026-10-01', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Масло'), 'Охра желтая', '029', 'тюбик', 0, 1.0, NULL, '2026-10-01', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Масло'), 'Телесная', '046', 'тюбик', 0, NULL, NULL, '2026-10-01', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Масло'), 'Красная прочная', '240', 'тюбик', 2.0, NULL, 1.0, '2026-10-01', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Масло'), 'Желтая средняя', '023', 'тюбик', 0, 1.0, NULL, '2026-10-01', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Масло'), 'Охра золотистая', '048', 'тюбик', 1.0, NULL, NULL, '2026-10-01', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Масло'), 'Сиена натуральная', '083', 'тюбик', 0, NULL, NULL, '2026-10-01', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Масло'), 'Лимонная желтая', '021', 'тюбик', 1.0, NULL, 1.0, '2026-10-01', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Масло'), 'Золотистая', '144', 'тюбик', 1.0, NULL, 1.0, '2026-10-01', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Масло'), 'Серебристая', '142', 'тюбик', 0, NULL, 1.0, '2026-10-01', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Масло'), 'Кадмий красный', '014', 'тюбик', 1.0, NULL, NULL, '2026-10-01', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Масло'), 'Розовая', '009', 'тюбик', 1.0, NULL, NULL, '2026-10-01', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Масло'), 'Киноварь', '006', 'тюбик', 2.0, NULL, 1.0, '2026-10-01', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Масло'), 'Оранжево-красная', '007', 'тюбик', 2.0, NULL, 1.0, '2026-10-01', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Масло'), 'красная темная', '001', 'тюбик', 1.0, NULL, NULL, '2026-10-01', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Масло'), 'Фиолетовая темная', '091', 'тюбик', 1.0, 1.0, NULL, '2026-10-01', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Масло'), 'Церулеум', '036', 'тюбик', 1.0, NULL, 1.0, '2026-10-01', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Масло'), 'Голубая фц', '039', 'тюбик', 0, NULL, NULL, '2026-10-01', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Масло'), 'Небесно голубая', '035', 'тюбик', 0, NULL, NULL, '2026-10-01', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Масло'), 'Кобальт синий', '038', 'тюбик', 1.0, NULL, NULL, '2026-10-01', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Масло'), 'Ультрамарин', '033', 'тюбик', 0, NULL, NULL, '2026-10-01', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Масло'), 'Травяная светлая', '066', 'тюбик', 2.0, NULL, 1.0, '2026-10-01', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Масло'), 'Оливковая', '069', 'тюбик', 2.0, NULL, 1.0, '2026-10-01', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Масло'), 'Салатовая', '071', 'тюбик', 1.0, NULL, 1.0, '2026-10-01', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Масло'), 'Виридоновая зеленая', '067', 'тюбик', 1.0, NULL, NULL, '2026-10-01', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Масло'), 'Сиренево- синяя светлая', '369', 'тюбик', 1.0, NULL, 1.0, '2026-10-01', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Масло'), 'Травяная', '106', 'тюбик', 0, 1.0, NULL, '2026-10-01', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Масло'), 'Умбра натуральная', '085', 'тюбик', 1.0, 1.0, NULL, '2026-10-01', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Масло'), 'Холодная серая', '059', 'тюбик', 1.0, NULL, 1.0, '2026-10-01', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Масло'), 'Сажа газовая', '052', 'тюбик', 0, NULL, NULL, '2026-10-01', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Масло'), 'Умбра жженая', '084', 'тюбик', 1.0, NULL, 1.0, '2026-10-01', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Масло'), 'Белила титановые 170 мл', '044', 'тюбик', 1.0, NULL, NULL, '2026-10-01', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Масло'), 'Белила титановые 46 мл', '044', 'тюбик', 0, NULL, NULL, '2026-10-01', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Масло'), 'Ван Дик коричневый', '088', 'тюбик', 1.0, NULL, NULL, '2026-10-01', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Масло'), 'красно-коричневая', '012', 'тюбик', 1.0, NULL, NULL, '2026-10-01', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Масло'), 'Мастер класс', NULL, 'тюбик', 0, NULL, NULL, '2026-10-01', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Масло'), 'Травяная зеленая', '716', 'тюбик', 0, NULL, NULL, '2026-10-01', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Масло'), 'Гамма', NULL, 'тюбик', 0, NULL, NULL, '2026-10-01', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Масло'), 'Краплак красный темный', '301', 'тюбик', 1.0, 1.0, 1.0, '2026-10-01', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Масло'), 'английская красная', '207', 'тюбик', 1.0, NULL, NULL, '2026-10-01', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Масло'), 'индиго экстра', '518', 'тюбик', 1.0, NULL, NULL, '2026-10-01', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Масло'), 'Виста артиста', NULL, 'тюбик', 0, NULL, NULL, '2026-10-01', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Масло'), 'Красно коричневый', '017', 'тюбик', 0, NULL, NULL, '2026-10-01', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Масло'), 'изостудия', NULL, 'тюбик', 0, NULL, NULL, '2026-10-01', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Масло'), 'ультрамарин', '511', 'тюбик', 1.0, NULL, NULL, '2026-10-01', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Масло'), 'сажа газовая', '813', 'тюбик', 0, NULL, NULL, '2026-10-01', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Масло'), 'Окись хрома', '608', 'тюбик', 0, NULL, 1.0, '2026-10-01', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Масло'), 'неаполетанская желтая', '127', 'тюбик', 0, 1.0, NULL, '2026-10-01', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Масло'), 'звездный цвет', NULL, 'тюбик', 0, NULL, NULL, '2026-10-01', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Масло'), 'белила титановые 200 мл', NULL, 'тюбик', 0, NULL, NULL, '2026-10-01', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Масло'), 'телесная', '202', 'тюбик', 0, 1.0, NULL, '2026-10-01', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Масло'), 'Малевич', NULL, 'тюбик', 0, NULL, NULL, '2026-10-01', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Масло'), 'Травяная светлая', '105', 'тюбик', 0, NULL, NULL, '2026-10-01', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Масло'), 'Телесная', '719', 'тюбик', 0, NULL, NULL, '2026-10-01', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Масло'), 'Сиена Натуральная', '494', 'тюбик', 0, NULL, NULL, '2026-10-01', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Масло'), 'Кадмий красный тёный', '300', 'тюбик', 0, NULL, NULL, '2026-10-01', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Масло'), 'Кадмий жёлтый тёмный', '712', 'тюбик', 0, NULL, NULL, '2026-10-01', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Масло'), 'белила титановые', NULL, 'тюбик', 0, NULL, NULL, '2026-10-01', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Масло'), 'изо студия черная', NULL, 'тюбик', 0, NULL, 1.0, '2026-10-01', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Масло'), 'Тициан', NULL, 'тюбик', 0, NULL, NULL, '2026-10-01', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Масло'), 'Кадмий оранжевый', '115', 'тюбик', 1.0, NULL, NULL, '2026-10-01', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Масло'), 'голубая фц', '160', 'тюбик', 0, 1.0, NULL, '2026-10-01', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Масло'), 'Сиена Натуральная', '494', 'тюбик', 1.0, NULL, NULL, '2026-10-01', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акрил'), 'Брауберг 75 мл', NULL, 'тюбик', 0, NULL, NULL, NULL, NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акрил'), 'Умбра жженая', '084', 'тюбик', 0, 1.0, NULL, '2026-10-01', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акрил'), 'Умбра натуральная', '084', 'тюбик', 0, 1.0, NULL, '2026-10-01', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акрил'), 'Красно-коричневый', '012', 'тюбик', 2.0, 1.0, 1.0, '2026-10-01', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акрил'), 'Салатовая', '071', 'тюбик', 0, NULL, NULL, NULL, NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акрил'), 'Красная темная', '001', 'тюбик', 0, 2.0, NULL, NULL, NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акрил'), 'Киноварь', '006', 'тюбик', 1.0, 1.0, NULL, NULL, NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акрил'), 'оранжево желтая', '026', 'тюбик', 2.0, NULL, NULL, '2026-10-01', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акрил'), 'голубая фц', '039', 'тюбик', 1.0, NULL, NULL, NULL, NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акрил'), 'прусская синяя', '031', 'тюбик', 1.0, NULL, 1.0, NULL, NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акрил'), 'небесно-голубая', '035', 'тюбик', 1.0, NULL, NULL, NULL, NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акрил'), 'фиолетовая средняя', '095', 'тюбик', 1.0, NULL, 1.0, '2026-10-01', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акрил'), 'Серо-голубая светлая', '331', 'тюбик', 1.0, NULL, NULL, NULL, NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акрил'), 'телесная', '046', 'тюбик', 1.0, NULL, NULL, NULL, NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акрил'), 'Желтая средняя', '023', 'тюбик', 1.0, NULL, NULL, NULL, NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акрил'), 'охра желтая', '029', 'тюбик', 1.0, 1.0, NULL, NULL, NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акрил'), 'Лимонная желтая', '021', 'тюбик', 1.0, 2.0, NULL, NULL, NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акрил'), 'Зеленая светлая', '062', 'тюбик', 1.0, NULL, 1.0, NULL, NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акрил'), 'Прусская зеленая', '056', 'тюбик', 1.0, 1.0, 2.0, '2026-10-01', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акрил'), 'розовая', '310', 'тюбик', 1.0, NULL, NULL, '2026-10-01', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акрил'), 'персиковая красная', '010', 'тюбик', 1.0, NULL, NULL, '2026-10-01', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акрил'), 'розовая светлая', '019', 'тюбик', 1.0, NULL, 1.0, '2026-10-01', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акрил'), 'фиолетовая темная', '091', 'тюбик', 0, NULL, NULL, NULL, NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акрил'), 'фиолетовая светлая', '334', 'тюбик', 0, NULL, NULL, NULL, NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акрил'), 'золотистая', '144', 'тюбик', 1.0, NULL, 1.0, '2026-10-01', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акрил'), 'серебристая', '142', 'тюбик', 0, NULL, NULL, NULL, NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акрил'), 'ультрамарин', '033', 'тюбик', 2.0, 1.0, NULL, '2026-10-01', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акрил'), 'Травяная зеленая', '066', 'тюбик', 3.0, NULL, 2.0, '2026-10-01', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акрил'), 'виридоновая зеленая', '067', 'тюбик', 2.0, NULL, 1.0, NULL, NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акрил'), 'черная', '051', 'тюбик', 0, NULL, NULL, NULL, NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акрил'), 'белила титановые', '044', 'тюбик', 1.0, NULL, NULL, '2026-10-01', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акрил'), 'сиена жженая', '082', 'тюбик', 1.0, NULL, NULL, '2026-10-01', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акрил'), 'ладога 75 мл', NULL, 'тюбик', 0, NULL, NULL, NULL, NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акрил'), 'ультрамарин', '511', 'тюбик', 2.0, NULL, NULL, '2026-10-01', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акрил'), 'Синяя', '515', 'тюбик', 1.0, NULL, NULL, '2026-10-01', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акрил'), 'белила титановые', '044', 'тюбик', 0, NULL, NULL, NULL, NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акрил'), 'окись хрома', '704', 'тюбик', 1.0, NULL, NULL, '2026-10-01', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акрил'), 'окись хрома', '608', 'тюбик', 0, NULL, NULL, NULL, NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акрил'), 'виста артиста 75 мл', NULL, 'тюбик', 0, NULL, NULL, NULL, NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акрил'), 'глянц бирюзовый', NULL, 'тюбик', 0, NULL, NULL, NULL, NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акрил'), 'матовый бирюзовый', NULL, 'тюбик', 0, NULL, NULL, NULL, NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акрил'), 'Розовый', '36', 'тюбик', 0, NULL, NULL, NULL, NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акрил'), 'Гамма', NULL, 'тюбик', 0, NULL, NULL, NULL, NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акрил'), 'английская красная', '207.0', 'тюбик', 0, NULL, NULL, NULL, NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акрил'), 'сонет 75 мл', NULL, 'тюбик', 0, NULL, NULL, NULL, NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акрил'), 'фиолетовая темная', '606', 'тюбик', 0, 1.0, NULL, NULL, NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акрил'), 'Банки 250 мл', NULL, 'тюбик', 0, NULL, NULL, NULL, NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акрил'), 'черный', '051', 'тюбик', 0, NULL, 2.0, NULL, NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акрил'), 'белый', '044', 'тюбик', 0, NULL, 1.0, NULL, NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акрил'), 'небесно-голубая', NULL, 'тюбик', 0, NULL, NULL, NULL, NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акрил'), 'ультрамарин', NULL, 'тюбик', 0, NULL, NULL, NULL, NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акрил'), 'телесная', '046', 'тюбик', 0, 1.0, NULL, NULL, NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акрил'), 'темперная краска', NULL, 'тюбик', 0, NULL, NULL, NULL, NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акрил'), 'темперная кадми оранжевый', '304.0', 'тюбик', 0.5, NULL, NULL, '2026-10-01', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акрил'), 'темперная сажа газовая', '801.0', 'тюбик', 0.5, NULL, NULL, '2026-10-01', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акрил'), 'темперная сиена жженая', '406.0', 'тюбик', 1.0, NULL, NULL, '2026-10-01', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акрил'), 'темперная белила титановые', '101.0', 'тюбик', 1.0, NULL, NULL, '2026-10-01', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акрил'), 'темперная краплак красные', '317.0', 'тюбик', 1.0, NULL, NULL, '2026-10-01', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акрил'), 'темперная церулиум', '503.0', 'тюбик', 1.0, NULL, NULL, '2026-10-01', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акрил'), 'темперная кадми красный', '303.0', 'тюбик', 1.0, NULL, NULL, '2026-10-01', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акрил'), 'Акрил брауберг 1л черный', '051', 'тюбик', 0, 1.0, NULL, NULL, NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акрил'), 'брауберг белила глянцевые 1л', '044', 'тюбик', 0, NULL, NULL, NULL, NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акрил'), 'сонет фиолетовый темный', NULL, 'тюбик', 0, NULL, NULL, NULL, NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акрил'), 'акрил брауберг черный 250мл', NULL, 'тюбик', 0, NULL, NULL, NULL, NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Гуашь'), 'Гуашь белая 500мл', NULL, 'тюбик', 1.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Гуашь'), 'Гуашь желтая светлая 40мл', NULL, 'тюбик', 2.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Гуашь'), 'Гуашь охра светлая', NULL, 'тюбик', 5.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Гуашь'), 'Гуашь коричневая (умбра жженая)', NULL, 'тюбик', 5.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Гуашь'), 'Гуашь красная (краплак)', NULL, 'тюбик', 3.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Гуашь'), 'Гуашь красная 40мл', NULL, 'тюбик', 6.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Гуашь'), 'Гуашь фиолетовая светлая', NULL, 'тюбик', 3.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Гуашь'), 'гуашь ультрамарин 100 мл', NULL, 'тюбик', 1.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Гуашь'), 'гуашь ультрамарин 40 мл', NULL, 'тюбик', 4.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Гуашь'), 'Гуашь синяя', NULL, 'тюбик', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Гуашь'), 'Гуашь бирюзовая', NULL, 'тюбик', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Гуашь'), 'Гуашь зеленая темная', NULL, 'тюбик', 4.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Гуашь'), 'Гуашь зеленая яркая', NULL, 'тюбик', 5.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Гуашь'), 'Гуашь оливковая', NULL, 'тюбик', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Гуашь'), 'Гуашь черная (сажа газовая)', NULL, 'тюбик', 3.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Гуашь'), 'Гуашь набор сонет', NULL, 'тюбик', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Гуашь'), 'Гуашь набор м.к.', NULL, 'тюбик', 3.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Гуашь'), 'Гуашь черная', '051', 'тюбик', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Гуашь'), 'Гуашь лазурь желеная', NULL, 'тюбик', 4.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Гуашь'), 'Гуашь коричневая', NULL, 'тюбик', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Гуашь'), 'Гуашь розовая', NULL, 'тюбик', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Гуашь'), 'белила титановые 40', NULL, 'тюбик', 2.0, NULL, NULL, NULL, NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Гуашь'), 'красная желц', NULL, 'тюбик', 1.0, NULL, NULL, NULL, NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Гуашь'), 'гуашь белила 500 мл', NULL, 'тюбик', 1.0, NULL, NULL, NULL, NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акварель'), 'сонет 16', NULL, 'кювета', 4.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акварель'), 'сонет 24', NULL, 'кювета', 14.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акварель'), 'Брауберг', NULL, 'кювета', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акварель'), 'Белила титановые', '44.0', 'кювета', 2.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акварель'), 'Лимонная желтая', '21.0', 'кювета', 5.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акварель'), 'Жёлтая светлая', '22.0', 'кювета', 4.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акварель'), 'Гуммигут', '28.0', 'кювета', 4.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акварель'), 'Охра жёлтая', '29.0', 'кювета', 5.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акварель'), 'Ультрамарин', '33.0', 'кювета', 1.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акварель'), 'Церулеум', '36.0', 'кювета', 3.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акварель'), 'Кобальт синий', '38.0', 'кювета', 3.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акварель'), 'Голубая фц', '39.0', 'кювета', 6.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акварель'), 'Красная свелая', '3.0', 'кювета', 2.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акварель'), 'Киноварь', '6.0', 'кювета', 5.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акварель'), 'Оанево-красная', '7.0', 'кювета', 6.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акварель'), 'РОзовая', '9.0', 'кювета', 3.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акварель'), 'Травяная зелёная', '66.0', 'кювета', 6.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акварель'), 'Зелёная темная', '64.0', 'кювета', 4.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акварель'), 'Салатовая', '71.0', 'кювета', 6.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акварель'), 'Кармин', '110.0', 'кювета', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акварель'), 'Сиена жженая', '82.0', 'кювета', 4.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акварель'), 'Умбра жженая', '84.0', 'кювета', 7.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акварель'), 'Умбра натууральная', '85.0', 'кювета', 5.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акварель'), 'Чёрная', '51.0', 'кювета', 4.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акварель'), 'Зелёная фц', '72.0', 'кювета', 7.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акварель'), 'Фиолетовая тёмнаая', '91.0', 'кювета', 1.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акварель'), 'Фиолетовая тёмнаая', '95.0', 'кювета', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акварель'), 'Белые ночи', NULL, 'кювета', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акварель'), 'Акварель жёлтая темная', NULL, 'кювета', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акварель'), 'Акварель охра золотистая', NULL, 'кювета', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акварель'), 'Акварель оранжевая', NULL, 'кювета', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акварель'), 'Акварель красная светлач', NULL, 'кювета', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акварель'), 'Акварель карминовая', '319.0', 'кювета', 1.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акварель'), 'Акварель краплак красный', NULL, 'кювета', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акварель'), 'Акварель Английская красная', NULL, 'кювета', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акварель'), 'Акварель голубая', NULL, 'кювета', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акварель'), 'Акварель ультрамарин', '511.0', 'кювета', 1.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акварель'), 'Акварель синяя', NULL, 'кювета', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акварель'), 'Акварель сине-зеленая', NULL, 'кювета', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акварель'), 'Акварель фиолетовая светлач', '607.0', 'кювета', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акварель'), 'Акварель изумрудная', '713.0', 'кювета', 1.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акварель'), 'Акварель Сиена натуральная', NULL, 'кювета', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акварель'), 'Акварель Сиена жженая', NULL, 'кювета', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акварель'), 'Акварель умбра жженая', NULL, 'кювета', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акварель'), 'Акварель сепия', '292.0', 'кювета', 1.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акварель'), 'Акварель сажа газовая', NULL, 'кювета', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акрил по ткани'), 'Оливковая', NULL, 'тюбик', 1.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акрил по ткани'), 'Зеленая', NULL, 'тюбик', 0.5, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акрил по ткани'), 'Турецкая зеленая', NULL, 'тюбик', 1.5, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акрил по ткани'), 'зеленая средняя', NULL, 'тюбик', 1.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акрил по ткани'), 'Голубая', NULL, 'тюбик', 1.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акрил по ткани'), 'Бирюзовая', NULL, 'тюбик', 1.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акрил по ткани'), 'Светло-голубая', NULL, 'тюбик', 1.5, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акрил по ткани'), 'Серо-голубая', NULL, 'тюбик', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акрил по ткани'), 'Серая в черной банке', NULL, 'тюбик', 1.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акрил по ткани'), 'Ультрамарин', NULL, 'тюбик', 1.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акрил по ткани'), 'Фиолетовая темная', NULL, 'тюбик', 1.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акрил по ткани'), 'Черная Ладога', NULL, 'тюбик', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акрил по ткани'), 'Фиолетовая светлая', NULL, 'тюбик', 2.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акрил по ткани'), 'Флуорисцентная', NULL, 'тюбик', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акрил по ткани'), 'Розовая', NULL, 'тюбик', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акрил по ткани'), 'Красная', NULL, 'тюбик', 1.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акрил по ткани'), 'Желтая', NULL, 'тюбик', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акрил по ткани'), 'Желтая средняя', NULL, 'тюбик', 1.5, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акрил по ткани'), 'Сакура', NULL, 'тюбик', 1.5, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акрил по ткани'), 'Слоновая кость', NULL, 'тюбик', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акрил по ткани'), 'Розовая светлая', NULL, 'тюбик', 1.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акрил по ткани'), 'Коричневая', NULL, 'тюбик', 1.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акрил по ткани'), 'Оранжевая', NULL, 'тюбик', 1.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акрил по ткани'), 'Карминовая', NULL, 'тюбик', 2.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акрил по ткани'), 'Ультра черная декола', NULL, 'тюбик', 1.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акрил по ткани'), 'Черная', NULL, 'тюбик', 2.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акрил по ткани'), 'Черная idea', NULL, 'тюбик', 1.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акрил по ткани'), 'Розовая темная', NULL, 'тюбик', 1.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акрил по ткани'), 'Белая декола', NULL, 'тюбик', 1.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акрил по ткани'), 'Белая перламутровая', NULL, 'тюбик', 1.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акрил по ткани'), 'Телесная', NULL, 'тюбик', 1.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акрил по ткани'), 'Серебро', NULL, 'тюбик', 2.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акрил по ткани'), 'золото', NULL, 'тюбик', 2.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акрил по ткани'), 'бежевая', NULL, 'тюбик', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акрил по ткани'), 'небесно-голубая', NULL, 'тюбик', 2.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акрил по ткани'), 'фиолетовая', NULL, 'тюбик', 1.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акрил по ткани'), 'экстра белая', NULL, 'тюбик', 1.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акрил по ткани'), 'синяя', NULL, 'тюбик', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акрил по ткани'), 'синяя темная', NULL, 'тюбик', 1.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акрил по ткани'), 'изумрудная', NULL, 'тюбик', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акрил по ткани'), 'флюорисцентная', NULL, 'тюбик', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акрил по ткани'), 'контур decola black', NULL, 'тюбик', 1.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Акрил по ткани'), 'контур decola white', NULL, 'тюбик', 1.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Бумага'), 'Бумага для черчения (папка А2)', NULL, 'шт', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Бумага'), 'Бумага для черчения (папка А3)', NULL, 'шт', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Бумага'), 'Бумага для черчения (папка А5)', NULL, 'шт', 27.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Бумага'), 'Акварельная бумага (папка А2)', NULL, 'шт', 9.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Бумага'), 'Акварельная бумага (папка А3)', NULL, 'шт', 9.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Бумага'), 'Акварельная бумага (папка А4)', NULL, 'шт', 6.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Бумага'), 'Акварельная бумага (папка А5)', NULL, 'шт', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Бумага'), 'Бумага для пастели (папка А2)', NULL, 'шт', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Бумага'), 'Бумага для пастели (папка А3)', NULL, 'шт', 3.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Бумага'), 'Бумага для пастели (папка А4)', NULL, 'шт', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Бумага'), 'Писчая бумага', NULL, 'шт', 500.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Бумага'), 'Крафт бумага', NULL, 'шт', 43.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Бумага'), 'Копировальная чёрная', NULL, 'шт', 1.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Бумага'), 'цветная бумага', NULL, 'шт', 1.0, NULL, NULL, NULL, NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Бумага'), 'бумага для оригами', NULL, 'шт', 1.0, NULL, NULL, NULL, NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Холсты'), 'Холст на картоне 10/15', NULL, 'шт', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Холсты'), 'Холст на картоне 18/24', NULL, 'шт', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Холсты'), 'Холст на картоне 20/30', NULL, 'шт', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Холсты'), 'Холст на картоне 30/40', NULL, 'шт', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Холсты'), 'Холст на картоне 40/50', NULL, 'шт', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Холсты'), 'холст на картоне 50/60', NULL, 'шт', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Холсты'), 'Холст на картоне 50/70', NULL, 'шт', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Холсты'), 'Холст на подрамнике 18/24', NULL, 'шт', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Холсты'), 'Холст на подрамнике 20/30', NULL, 'шт', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Холсты'), 'Холст на подрамнике 30/40', NULL, 'шт', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Холсты'), 'Холст на подрамнике 50/70', NULL, 'шт', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Холсты'), 'Холст на картоне 10/10', NULL, 'шт', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Холсты'), 'Холст на картоне 15/20', NULL, 'шт', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Холсты'), 'холст на картоне 20/20', NULL, 'шт', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Холсты'), 'холст на картоне 25/35', NULL, 'шт', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Холсты'), 'холст на картоне 35/45', NULL, 'шт', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Холсты'), 'Холст на картоне 20/40', NULL, 'шт', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Холсты'), 'Холст на подрамнике 10/10', NULL, 'шт', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Холсты'), 'Холст на подрамнике 15/15', NULL, 'шт', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Холсты'), 'Холст на подрамнике 15/20', NULL, 'шт', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Холсты'), 'Холст на подрамнике 20/20', NULL, 'шт', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Холсты'), 'Холст на подрамнике 25/30', NULL, 'шт', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Холсты'), 'Холст на подрамнике 25/35', NULL, 'шт', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Холсты'), 'Холст на подрамнике 23/30', NULL, 'шт', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Холсты'), 'Холст на подрамнике 30/30', NULL, 'шт', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Холсты'), 'холст на подрамнике 30/40 3D', NULL, 'шт', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Холсты'), 'Холст на подрамнике 30/50', NULL, 'шт', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Холсты'), 'Холст на подрамнике 40 /40', NULL, 'шт', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Холсты'), 'Холст на подрамнике 40/50', NULL, 'шт', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Холсты'), 'Холст на подрамнике 50/60', NULL, 'шт', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Холсты'), 'Холст на подрамнике 60/60', NULL, 'шт', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Холсты'), 'Холст на подрамнике 80/60', NULL, 'шт', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Холсты'), 'холст на подрамнике круглый 40см', NULL, 'шт', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Холсты'), 'Значки', NULL, 'шт', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Холсты'), 'Круглые магниты', NULL, 'шт', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Холсты'), 'Квадратные магниты', NULL, 'шт', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Холсты'), 'Большой грунтованный картон', NULL, 'шт', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Холсты'), 'Негрунтованный картон 20/27', NULL, 'шт', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Холсты'), 'Набор холстов на подрамнике 24/30', NULL, 'шт', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Холсты'), 'Набор холстов на подрамнике 30/40', NULL, 'шт', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Холсты'), 'Набор холстов на подрамнике 40/50', NULL, 'шт', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Холсты'), 'Набор холстов на подрамнике 50/70', NULL, 'шт', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Аккаунтская (НЗ запас)'), 'Бумага для черчения (папка А2)', NULL, 'шт', 0, NULL, NULL, '2026-07-11', '-'),
  ((SELECT id FROM public.material_categories WHERE name = 'Аккаунтская (НЗ запас)'), 'Бумага для черчения (папка А3) - 10 л', NULL, 'шт', 3.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Аккаунтская (НЗ запас)'), 'Бумага для черчения (папка А5)', NULL, 'шт', 0, NULL, NULL, '2026-07-11', '-'),
  ((SELECT id FROM public.material_categories WHERE name = 'Аккаунтская (НЗ запас)'), 'Акварельная бумага (папка А2)', NULL, 'шт', 0, NULL, NULL, '2026-07-11', '-'),
  ((SELECT id FROM public.material_categories WHERE name = 'Аккаунтская (НЗ запас)'), 'Акварельная бумага (папка А3)', NULL, 'шт', 1.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Аккаунтская (НЗ запас)'), 'Акварельная бумага (папка А4)', NULL, 'шт', 2.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Аккаунтская (НЗ запас)'), 'Акварельная бумага (папка А5)', NULL, 'шт', 0, NULL, NULL, '2026-07-11', '-'),
  ((SELECT id FROM public.material_categories WHERE name = 'Аккаунтская (НЗ запас)'), 'Гуашь белая 500л', NULL, 'шт', 1.0, NULL, NULL, '2026-10-02', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Аккаунтская (НЗ запас)'), 'акрил черный 220мл', NULL, 'шт', 1.0, NULL, NULL, '2026-10-02', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Аккаунтская (НЗ запас)'), 'белила масло тюб. - 170', NULL, 'шт', 0, NULL, NULL, '2026-10-02', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Аккаунтская (НЗ запас)'), 'белила масло уп. - 200', NULL, 'шт', 1.0, NULL, NULL, '2026-10-02', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Аккаунтская (НЗ запас)'), 'пленка для палитр мал. 12,5 х 200м', NULL, 'шт', 3.0, NULL, NULL, '2026-10-02', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Аккаунтская (НЗ запас)'), 'пленка для палитр бол.', NULL, 'шт', 0, NULL, NULL, '2026-10-02', '-'),
  ((SELECT id FROM public.material_categories WHERE name = 'Аккаунтская (НЗ запас)'), 'холст 18 х 24 картон', NULL, 'шт', 6.0, NULL, NULL, '2026-10-02', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Аккаунтская (НЗ запас)'), 'холст 18 х 24 подрамник', NULL, 'шт', 1.0, NULL, NULL, '2026-10-02', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Аккаунтская (НЗ запас)'), 'холст 25 х 30 картон', NULL, 'шт', 3.0, NULL, NULL, '2026-10-02', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Аккаунтская (НЗ запас)'), 'холст 25 х 35 картон', NULL, 'шт', 7.0, NULL, NULL, '2026-10-02', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Аккаунтская (НЗ запас)'), 'холст 25 х 35 подрамник', NULL, 'шт', 1.0, NULL, NULL, '2026-10-02', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Аккаунтская (НЗ запас)'), 'холст 40 х 60 подрамник', NULL, 'шт', 1.0, NULL, NULL, '2026-10-02', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Аккаунтская (НЗ запас)'), 'холст 50 х 60 картон', NULL, 'шт', 1.0, NULL, NULL, '2026-10-02', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Аккаунтская (НЗ запас)'), 'холст 50 х 60 подрамник', NULL, 'шт', 1.0, NULL, NULL, '2026-10-02', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Аккаунтская (НЗ запас)'), 'холст 50 х 70 подрамник', NULL, 'шт', 2.0, NULL, NULL, '2026-10-02', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Аккаунтская (НЗ запас)'), 'масло льняное 250', NULL, 'шт', 3.0, NULL, NULL, '2026-10-02', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Аккаунтская (НЗ запас)'), 'разбавитель 250', NULL, 'шт', 2.0, NULL, NULL, '2026-10-02', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Кисти'), 'Белка 1', NULL, 'шт', 2.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Кисти'), 'Белка 2', NULL, 'шт', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Кисти'), 'Белка 3', NULL, 'шт', 8.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Кисти'), 'Белка 4', NULL, 'шт', 2.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Кисти'), 'Белка 5', NULL, 'шт', 5.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Кисти'), 'Белка 6', NULL, 'шт', 5.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Кисти'), 'Белка 7', NULL, 'шт', 4.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Кисти'), 'Белка 8', NULL, 'шт', 3.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Кисти'), 'Коза 3', NULL, 'шт', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Кисти'), 'Пони 2', NULL, 'шт', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Кисти'), 'Пони 6', NULL, 'шт', 6.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Кисти'), 'Синтетика круглая 00', NULL, 'шт', 3.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Кисти'), 'Снтетика круглая длинная ручка 1', NULL, 'шт', 7.0, NULL, NULL, '2026-07-11', '6+1'),
  ((SELECT id FROM public.material_categories WHERE name = 'Кисти'), 'Синтетика круглая 1', NULL, 'шт', 4.0, NULL, NULL, '2026-07-11', '3+1'),
  ((SELECT id FROM public.material_categories WHERE name = 'Кисти'), 'Синтетика круглая 2', NULL, 'шт', 6.0, NULL, NULL, '2026-07-11', '4+2'),
  ((SELECT id FROM public.material_categories WHERE name = 'Кисти'), 'Синтетика круглая 3', NULL, 'шт', 2.0, NULL, NULL, '2026-07-11', '1+1'),
  ((SELECT id FROM public.material_categories WHERE name = 'Кисти'), 'Синтетика круглая 4', NULL, 'шт', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Кисти'), 'Синтетика круглая 6', NULL, 'шт', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Кисти'), 'Синтетика круглая 7', NULL, 'шт', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Кисти'), 'Синтетика круглая 8', NULL, 'шт', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Кисти'), 'Синтетика круглая длинная ручка 3', NULL, 'шт', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Кисти'), 'Синтетика овальная 3', NULL, 'шт', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Кисти'), 'Синтетика плоская щетина 10', NULL, 'шт', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Кисти'), 'Синтетика плоская 8', NULL, 'шт', 12.0, NULL, NULL, '2026-07-11', '8+4'),
  ((SELECT id FROM public.material_categories WHERE name = 'Кисти'), 'плоская щетина 8', NULL, 'шт', 1.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Кисти'), 'Синтетика плоская круглая 8', NULL, 'шт', 2.0, NULL, NULL, '2026-07-11', '1+1'),
  ((SELECT id FROM public.material_categories WHERE name = 'Кисти'), 'Синтетика плоская 12', NULL, 'шт', 5.0, NULL, NULL, '2026-07-11', '2+3'),
  ((SELECT id FROM public.material_categories WHERE name = 'Кисти'), 'Синтетика плоская 14', NULL, 'шт', 2.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Кисти'), 'Синтетика плоская 26', NULL, 'шт', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Кисти'), 'Синтетика плоская 3', NULL, 'шт', 4.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Кисти'), 'Синтетика плоская 30', NULL, 'шт', 1.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Кисти'), 'Синтетика плоская 4', NULL, 'шт', 4.0, NULL, NULL, '2026-07-11', '2+2'),
  ((SELECT id FROM public.material_categories WHERE name = 'Кисти'), 'Синтетика плоская 5', NULL, 'шт', 4.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Кисти'), 'Синтетика плоская 6', NULL, 'шт', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Кисти'), 'Синтетика плоская 7', NULL, 'шт', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Кисти'), 'Синтетика плоская 9', NULL, 'шт', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Кисти'), 'Синтетика плоская 10', NULL, 'шт', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Кисти'), 'Синтетика скошенная 10', NULL, 'шт', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Кисти'), 'Синтетика скошенная 26', NULL, 'шт', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Кисти'), 'Синтетика флейцевая длинная ручка', NULL, 'шт', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Кисти'), 'Щетина 50', NULL, 'шт', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Кисти'), 'Щетина 7', NULL, 'шт', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Кисти'), 'СИНТЕТИКА ПЛОСКАЯ 24', NULL, 'шт', 1.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Кисти'), 'Плоская щетина 12', NULL, 'шт', 3.0, NULL, NULL, '2026-07-11', '1+2'),
  ((SELECT id FROM public.material_categories WHERE name = 'Кисти'), 'Синтетика плоская 50', NULL, 'шт', 1.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Кисти'), 'Синтетика плоская 75', NULL, 'шт', 1.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Кисти'), 'Синтетика плоская 100', NULL, 'шт', 1.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Кисти'), 'плоская щетина 20', NULL, 'шт', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Кисти'), 'синтетика круглая 5', NULL, 'шт', 2.0, NULL, NULL, '2026-07-11', '1+1'),
  ((SELECT id FROM public.material_categories WHERE name = 'Кисти'), 'беличья кисть 8', NULL, 'шт', 1.0, NULL, NULL, NULL, NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Кисти'), 'беличья кисть 6', NULL, 'шт', 1.0, NULL, NULL, NULL, NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Кисти'), 'беличья кисть 5', NULL, 'шт', 1.0, NULL, NULL, NULL, NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Кисти'), 'brau 00', NULL, 'шт', 3.0, NULL, NULL, NULL, NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Кисти'), 'brau 1', NULL, 'шт', 2.0, NULL, NULL, NULL, NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Кисти'), 'pinax 1 111 щетина', NULL, 'шт', 5.0, NULL, NULL, NULL, NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Кисти'), 'pinax 1 751 синт', NULL, 'шт', 1.0, NULL, NULL, NULL, NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Кисти'), 'pinax 3 771 белка имитация', NULL, 'шт', 2.0, NULL, NULL, NULL, NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Кисти'), 'pinax 2 991 синт', NULL, 'шт', 2.0, NULL, NULL, NULL, NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Кисти'), 'pinax 8 684 синт', NULL, 'шт', 1.0, NULL, NULL, NULL, NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Кисти'), 'pinax 6 684 синт', NULL, 'шт', 1.0, NULL, NULL, NULL, NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Кисти'), 'pinax 10 684 синт', NULL, 'шт', 1.0, NULL, NULL, NULL, NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Кисти'), 'pinax 16 684 синт', NULL, 'шт', 1.0, NULL, NULL, NULL, NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Кисти'), 'pinax 12 244 синт', NULL, 'шт', 3.0, NULL, NULL, NULL, NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Кисти'), 'pinax 8 354 синт', NULL, 'шт', 4.0, NULL, NULL, NULL, NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Кисти'), 'pinax 20 684 синт', NULL, 'шт', 1.0, NULL, NULL, NULL, NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Карандаши'), 'H1', NULL, 'шт', 2.0, 6.0, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Карандаши'), 'H2', NULL, 'шт', 3.0, 7.0, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Карандаши'), 'H3', NULL, 'шт', 4.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Карандаши'), 'H4', NULL, 'шт', 3.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Карандаши'), 'H5', NULL, 'шт', 3.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Карандаши'), 'H6', NULL, 'шт', 4.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Карандаши'), 'H7', NULL, 'шт', 3.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Карандаши'), 'H8', NULL, 'шт', 4.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Карандаши'), 'B1', NULL, 'шт', 4.0, 7.0, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Карандаши'), 'B2', NULL, 'шт', 4.0, 11.0, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Карандаши'), 'B3', NULL, 'шт', 3.0, 1.0, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Карандаши'), 'B4', NULL, 'шт', 6.0, 4.0, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Карандаши'), 'B5', NULL, 'шт', 3.0, 1.0, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Карандаши'), 'B6', NULL, 'шт', 6.0, 1.0, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Карандаши'), 'B7', NULL, 'шт', 4.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Карандаши'), 'B8', NULL, 'шт', 4.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Карандаши'), 'HB', NULL, 'шт', 10.0, 14.0, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Прочие худ.материалы'), 'пастель 72 цвета', NULL, 'шт', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Прочие худ.материалы'), 'пастель 16 цветов', NULL, 'шт', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Прочие худ.материалы'), 'пастель 64 цвета', NULL, 'шт', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Прочие худ.материалы'), 'пастель 24 цвета', NULL, 'шт', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Прочие худ.материалы'), 'Угольный карандаш черный', NULL, 'шт', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Прочие худ.материалы'), 'Угольный карандаш белый', NULL, 'шт', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Прочие худ.материалы'), 'Пастельные карандаши белые', NULL, 'шт', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Прочие худ.материалы'), 'Мастихин', NULL, 'шт', 5.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Прочие худ.материалы'), 'Мастихин фигурный', NULL, 'шт', 4.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Прочие худ.материалы'), 'Мастихин другие', NULL, 'шт', 6.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Прочие худ.материалы'), 'Маслёнка с крыш 5см', NULL, 'шт', 4.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Прочие худ.материалы'), 'Разбавитель слабопахнущий', NULL, 'шт', 0.5, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Прочие худ.материалы'), 'Лак стирольный', NULL, 'шт', 2.5, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Прочие худ.материалы'), 'Разбавители масло льняное', NULL, 'шт', 0.5, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Прочие худ.материалы'), 'разбавитель акрила по ткани', NULL, 'шт', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Прочие худ.материалы'), 'РАЗБАВИТЕЛЬ ДЛЯ АКРИЛА ГАММА', NULL, 'шт', 0, NULL, NULL, NULL, NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Прочие худ.материалы'), 'ЛАК АКРИЛ МАТОВЫЙ', NULL, 'шт', 0, NULL, NULL, NULL, NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Прочие худ.материалы'), 'палитра', NULL, 'шт', 0, NULL, NULL, NULL, NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Прочие худ.материалы'), 'смойка масл красок 500мл', NULL, 'шт', 1.0, NULL, NULL, NULL, NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Канцелярия'), 'Офисная бумага', NULL, 'шт', 1.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Канцелярия'), 'Файлы плотные А4', NULL, 'шт', 1.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Канцелярия'), 'файлы А5', NULL, 'шт', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Канцелярия'), 'Держатель для карандаша', NULL, 'шт', 1.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Канцелярия'), 'Черная гелиевая ручка', NULL, 'шт', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Канцелярия'), 'Капилярная черная ручка', NULL, 'шт', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Канцелярия'), 'Белая гелиевая ручка', NULL, 'шт', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Канцелярия'), 'Циркули', NULL, 'шт', 1.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Канцелярия'), 'Линейка', NULL, 'шт', 3.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Канцелярия'), 'Ластик', NULL, 'шт', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Канцелярия'), 'Клячка', NULL, 'шт', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Канцелярия'), 'Скобки для степлера', NULL, 'шт', 1.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Канцелярия'), 'Скотч бумажный толстый', NULL, 'шт', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Канцелярия'), 'Скотч бумажный тонкий', NULL, 'шт', 3.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Канцелярия'), 'Фотобумага А4 глянц', NULL, 'шт', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Канцелярия'), 'Фотобумага самокл А4 135/м2', NULL, 'шт', 0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Канцелярия'), 'точилка', NULL, 'шт', 2.0, NULL, NULL, '2026-07-11', NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Хоз.Товары'), 'Жидкое мыло', NULL, 'шт', 0, NULL, NULL, NULL, NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Хоз.Товары'), 'Хозяйственное мыло', NULL, 'шт', 0, NULL, NULL, NULL, NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Хоз.Товары'), 'Средство для мытья туалета', NULL, 'шт', 0, NULL, NULL, NULL, NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Хоз.Товары'), 'Стредство для устранения засоров', NULL, 'шт', 0, NULL, NULL, NULL, NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Хоз.Товары'), 'Анти-графити', NULL, 'шт', 0, NULL, NULL, NULL, NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Хоз.Товары'), 'Стредство для мытья стекол', NULL, 'шт', 0, NULL, NULL, NULL, NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Хоз.Товары'), 'Мусорные пакеты 20л', NULL, 'шт', 0, NULL, NULL, NULL, NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Хоз.Товары'), 'Губки', NULL, 'шт', 0, NULL, NULL, NULL, NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Хоз.Товары'), 'Перчатки', NULL, 'шт', 0, NULL, NULL, NULL, NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Хоз.Товары'), 'Тряпки сменные для швабры', NULL, 'шт', 0, NULL, NULL, NULL, NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Хоз.Товары'), 'Тряпочки из микрофибры', NULL, 'шт', 0, NULL, NULL, NULL, NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Хоз.Товары'), 'Салфетки', NULL, 'шт', 0, NULL, NULL, NULL, NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Хоз.Товары'), 'Туалетная бумага', NULL, 'шт', 0, NULL, NULL, NULL, NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Хоз.Товары'), 'Полотенца вафельные для рук', NULL, 'шт', 0, NULL, NULL, NULL, NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Хоз.Товары'), 'мусорные пакеты 240 л.', NULL, 'шт', 0, NULL, NULL, NULL, NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Хоз.Товары'), 'Стаканы для кофе 0,25', NULL, 'шт', 0, NULL, NULL, NULL, NULL),
  ((SELECT id FROM public.material_categories WHERE name = 'Хоз.Товары'), 'Стаканы однораз 0.2', NULL, 'шт', 0, NULL, NULL, NULL, NULL);

-- Материалы для МК (актуальный список к мероприятиям, октябрь 2026)
INSERT INTO public.materials (category_id, name, unit, qty_full, last_counted_at) VALUES
  ((SELECT id FROM public.material_categories WHERE name = 'Материалы для МК'), 'холсты круглые 18 см', 'шт', 0, '2026-10-02'),
  ((SELECT id FROM public.material_categories WHERE name = 'Материалы для МК'), 'акрил: фиолетовая средняя 95', 'шт', 1.0, '2026-10-02'),
  ((SELECT id FROM public.material_categories WHERE name = 'Материалы для МК'), 'акрил: зеленая травяная', 'шт', 1.0, '2026-10-02'),
  ((SELECT id FROM public.material_categories WHERE name = 'Материалы для МК'), 'акрил: оливковый', 'шт', 1.0, '2026-10-02'),
  ((SELECT id FROM public.material_categories WHERE name = 'Материалы для МК'), 'акрил: желтая средняя', 'шт', 1.0, '2026-10-02'),
  ((SELECT id FROM public.material_categories WHERE name = 'Материалы для МК'), 'акрил: оранжево-желтая', 'шт', 1.0, '2026-10-02'),
  ((SELECT id FROM public.material_categories WHERE name = 'Материалы для МК'), 'акрил: серебристый акрил', 'шт', 1.0, '2026-10-02'),
  ((SELECT id FROM public.material_categories WHERE name = 'Материалы для МК'), 'акрил: акрил маджента', 'шт', 0, '2026-10-02'),
  ((SELECT id FROM public.material_categories WHERE name = 'Материалы для МК'), 'акрил: красная темная', 'шт', 1.0, '2026-10-02'),
  ((SELECT id FROM public.material_categories WHERE name = 'Материалы для МК'), 'акрил: черная 1 банка', 'шт', 1.0, '2026-10-02'),
  ((SELECT id FROM public.material_categories WHERE name = 'Материалы для МК'), 'акрил: белая 1 банка', 'шт', 1.0, '2026-10-02'),
  ((SELECT id FROM public.material_categories WHERE name = 'Материалы для МК'), 'холст 18*24', 'шт', 30.0, '2026-10-02'),
  ((SELECT id FROM public.material_categories WHERE name = 'Материалы для МК'), 'акварельная бумага А4', 'шт', 3.0, '2026-10-02'),
  ((SELECT id FROM public.material_categories WHERE name = 'Материалы для МК'), 'салфетки', 'шт', 4.0, '2026-10-02'),
  ((SELECT id FROM public.material_categories WHERE name = 'Материалы для МК'), 'зубочистки', 'шт', 1.0, '2026-10-02'),
  ((SELECT id FROM public.material_categories WHERE name = 'Материалы для МК'), 'клей пва 125 гр.', 'шт', 1.0, '2026-10-02'),
  ((SELECT id FROM public.material_categories WHERE name = 'Материалы для МК'), 'текстурная паста', 'шт', 0, '2026-10-02'),
  ((SELECT id FROM public.material_categories WHERE name = 'Материалы для МК'), 'пленка для защиты столов', 'шт', 0, '2026-10-02');

-- Заявки на закупку из списка "Метериалы для МК" (октябрь 2026)
INSERT INTO public.purchase_requests (cycle_label, material_id, needed_qty, available_qty, status) VALUES
  ('Октябрь 2026 (МК)', (SELECT id FROM public.materials WHERE category_id = (SELECT id FROM public.material_categories WHERE name = 'Материалы для МК') AND name = 'холсты круглые 18 см'), 12.0, 0, 'заказано'),
  ('Октябрь 2026 (МК)', (SELECT id FROM public.materials WHERE category_id = (SELECT id FROM public.material_categories WHERE name = 'Материалы для МК') AND name = 'акрил: фиолетовая средняя 95'), 1.0, 1.0, 'куплено'),
  ('Октябрь 2026 (МК)', (SELECT id FROM public.materials WHERE category_id = (SELECT id FROM public.material_categories WHERE name = 'Материалы для МК') AND name = 'акрил: зеленая травяная'), 1.0, 1.0, 'куплено'),
  ('Октябрь 2026 (МК)', (SELECT id FROM public.materials WHERE category_id = (SELECT id FROM public.material_categories WHERE name = 'Материалы для МК') AND name = 'акрил: оливковый'), 1.0, 1.0, 'куплено'),
  ('Октябрь 2026 (МК)', (SELECT id FROM public.materials WHERE category_id = (SELECT id FROM public.material_categories WHERE name = 'Материалы для МК') AND name = 'акрил: желтая средняя'), 1.0, 1.0, 'куплено'),
  ('Октябрь 2026 (МК)', (SELECT id FROM public.materials WHERE category_id = (SELECT id FROM public.material_categories WHERE name = 'Материалы для МК') AND name = 'акрил: оранжево-желтая'), 1.0, 1.0, 'куплено'),
  ('Октябрь 2026 (МК)', (SELECT id FROM public.materials WHERE category_id = (SELECT id FROM public.material_categories WHERE name = 'Материалы для МК') AND name = 'акрил: серебристый акрил'), 1.0, 1.0, 'куплено'),
  ('Октябрь 2026 (МК)', (SELECT id FROM public.materials WHERE category_id = (SELECT id FROM public.material_categories WHERE name = 'Материалы для МК') AND name = 'акрил: акрил маджента'), 1.0, 0, 'заказано'),
  ('Октябрь 2026 (МК)', (SELECT id FROM public.materials WHERE category_id = (SELECT id FROM public.material_categories WHERE name = 'Материалы для МК') AND name = 'акрил: красная темная'), 1.0, 1.0, 'куплено'),
  ('Октябрь 2026 (МК)', (SELECT id FROM public.materials WHERE category_id = (SELECT id FROM public.material_categories WHERE name = 'Материалы для МК') AND name = 'акрил: черная 1 банка'), 1.0, 1.0, 'куплено'),
  ('Октябрь 2026 (МК)', (SELECT id FROM public.materials WHERE category_id = (SELECT id FROM public.material_categories WHERE name = 'Материалы для МК') AND name = 'акрил: белая 1 банка'), 1.0, 1.0, 'куплено'),
  ('Октябрь 2026 (МК)', (SELECT id FROM public.materials WHERE category_id = (SELECT id FROM public.material_categories WHERE name = 'Материалы для МК') AND name = 'холст 18*24'), 30.0, 30.0, 'куплено'),
  ('Октябрь 2026 (МК)', (SELECT id FROM public.materials WHERE category_id = (SELECT id FROM public.material_categories WHERE name = 'Материалы для МК') AND name = 'акварельная бумага А4'), 3.0, 3.0, 'куплено'),
  ('Октябрь 2026 (МК)', (SELECT id FROM public.materials WHERE category_id = (SELECT id FROM public.material_categories WHERE name = 'Материалы для МК') AND name = 'салфетки'), 4.0, 4.0, 'куплено'),
  ('Октябрь 2026 (МК)', (SELECT id FROM public.materials WHERE category_id = (SELECT id FROM public.material_categories WHERE name = 'Материалы для МК') AND name = 'зубочистки'), 1.0, 1.0, 'куплено'),
  ('Октябрь 2026 (МК)', (SELECT id FROM public.materials WHERE category_id = (SELECT id FROM public.material_categories WHERE name = 'Материалы для МК') AND name = 'клей пва 125 гр.'), 1.0, 1.0, 'куплено'),
  ('Октябрь 2026 (МК)', (SELECT id FROM public.materials WHERE category_id = (SELECT id FROM public.material_categories WHERE name = 'Материалы для МК') AND name = 'текстурная паста'), 1.0, 0, 'заказано'),
  ('Октябрь 2026 (МК)', (SELECT id FROM public.materials WHERE category_id = (SELECT id FROM public.material_categories WHERE name = 'Материалы для МК') AND name = 'пленка для защиты столов'), 1.0, 0, 'заказано');
